name: checks

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20, 21]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint (ESLint)
        run: npm run lint

      - name: Format (Prettier)
        run: npm run format:ci

      - name: Build project
        run: npm run build
