name: checks

on: [push]

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint (ESLint)
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Format (Prettier)
        run: npm run format:ci
